# Generated by Django 5.0 on 2023-12-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
                ('active', models.IntegerField(choices=[(1, 'health + 1'), (2, 'health + 2'), (3, 'card + 1'), (4, 'card + 2'), (5, 'destroy'), (6, 'double'), (7, 'copy'), (8, 'phase'), (9, 'sort'), (10, 'swap 1'), (11, 'swaps 2'), (12, 'under')])),
                ('spend', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dangerous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pick', models.IntegerField()),
                ('life_point', models.IntegerField()),
            ],
        ),
    ]
