# Generated by Django 4.2.5 on 2023-12-10 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pick', models.IntegerField()),
                ('life_point', models.IntegerField()),
                ('active', models.IntegerField(choices=[(1, 'health + 1'), (2, 'health + 2'), (3, 'card + 1'), (4, 'card + 2'), (5, 'destroy'), (6, 'double'), (7, 'copy'), (8, 'phase'), (9, 'sort'), (10, 'swap 1')])),
            ],
            options={
                'verbose_name': 'Boss',
                'verbose_name_plural': 'Boss',
            },
        ),
        migrations.CreateModel(
            name='Dangerous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pick', models.IntegerField()),
                ('life_point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_point', models.IntegerField(default=20)),
                ('level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('age', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Robinson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
                ('active', models.IntegerField(choices=[(1, 'health + 1'), (2, 'health + 2'), (3, 'card + 1'), (4, 'card + 2'), (5, 'destroy'), (6, 'double'), (7, 'copy'), (8, 'phase'), (9, 'sort'), (10, 'swap 1'), (11, 'swaps 2'), (12, 'under'), (-1, 'max = 0'), (-2, 'health - 1'), (-3, 'health - 2'), (-4, 'stop')])),
                ('spend', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('type', models.IntegerField(choices=[(1, 'Normal'), (2, 'Age'), (3, 'Skill')])),
            ],
        ),
        migrations.CreateModel(
            name='graveRobinson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.robinson')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.game')),
            ],
            options={
                'verbose_name': 'graveRobinson',
                'verbose_name_plural': 'graveRobinson',
            },
        ),
        migrations.CreateModel(
            name='graveDangerous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.dangerous')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.game')),
            ],
            options={
                'verbose_name': 'graveDangerous',
                'verbose_name_plural': 'graveDangerous',
            },
        ),
        migrations.CreateModel(
            name='deckRobinson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.robinson')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.game')),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
            },
        ),
        migrations.CreateModel(
            name='deckDangerous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.dangerous')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.game')),
            ],
            options={
                'verbose_name': 'deckDangerous',
                'verbose_name_plural': 'deckDangerous',
            },
        ),
        migrations.CreateModel(
            name='deckBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.boss')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.game')),
            ],
            options={
                'verbose_name': 'deckBoss',
                'verbose_name_plural': 'deckBoss',
            },
        ),
    ]
