# Generated by Django 5.0 on 2023-12-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_gravedangerous_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='active',
            field=models.IntegerField(choices=[(0, 'none'), (1, '+ 2 per age card'), (2, 'use 2 life per draw'), (3, '+ 1 power on robinson card'), (4, 'use half robinson card')]),
        ),
        migrations.AlterField(
            model_name='deckrobinson',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
