# Generated by Django 5.0 on 2023-12-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_boss_active_alter_deckrobinson_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graverobinson',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
